package objets and configuration/unpackaged/objects/Custom_Content__c.object
<CustomObject>
    <fields>
        <fullName>ContentDocumentId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ContentDocumentId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Download_Url__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Download Url</label>
        <type>Url</type>
    </fields>
    <label>Custom Content</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Custom Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Contents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

package objets and configuration/unpackaged/classes/CustomVideoGallery.cls
public class CustomVideoGallery {
	@AuraEnabled
    public static Map<String,String> getVideo(List<String> videoIds){
        List<Custom_Content__c> ListContent  =  [select ContentDocumentId__c,Download_Url__c from Custom_Content__c where contentDocumentId__c IN :videoIds];
        
        Map<String,String> urls = new Map<String,String>();
        for(Integer i = 0; i < ListContent.size(); i++){
            urls.put(ListContent[i].ContentDocumentId__c,ListContent[i].Download_Url__c);
        }

        return urls;
    }
}