package objets and configuration/unpackaged/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Brand_Category__c</fullName>
        <description>“Ellen Community”</description>
        <label>Brand Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Consumer Package Goods</fullName>
                </value>
                <value>
                    <fullName>Beauty</fullName>
                </value>
                <value>
                    <fullName>Alcohol</fullName>
                </value>
                <value>
                    <fullName>Apparel</fullName>
                </value>
                <value>
                    <fullName>Banking</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Fashion</fullName>
                </value>
                <value>
                    <fullName>QSR/Fast Food</fullName>
                </value>
                <value>
                    <fullName>Financial Services</fullName>
                </value>
                <value>
                    <fullName>Food and Beverage</fullName>
                    <label>Food &amp; Beverage</label>
                </value>
                <value>
                    <fullName>Games</fullName>
                    <label>Games,Toys</label>
                </value>
                <value>
                    <fullName>Health and Wellness</fullName>
                    <label>Health &amp; Wellness</label>
                </value>
                <value>
                    <fullName>Household</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Mobile Phones</fullName>
                </value>
                <value>
                    <fullName>Packaged Foods</fullName>
                </value>
                <value>
                    <fullName>Restaurants</fullName>
                    <label>Restaurants,QSR,Fast Food</label>
                </value>
                <value>
                    <fullName>Retail</fullName>
                    <label>Retail,Apparel,Grocery</label>
                </value>
                <value>
                    <fullName>Technology / Electronics</fullName>
                </value>
                <value>
                    <fullName>Telecommunications</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
                <value>
                    <fullName>Events and Ticket Brokers</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Pet</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Consumer Electronics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Brand_Name__c</fullName>
        <description>“Ellen Community”</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name / Product</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <description>“Ellen Community”</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Budget</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Details_of_Marketing_Campaign__c</fullName>
        <description>Ellen Community</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Details of Marketing Campaign</label>
        <length>3000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Important_things_about_Brand__c</fullName>
        <description>Ellen Community</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Important things about Brand</label>
        <length>3000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Main_KPIs__c</fullName>
        <description>Ellen Community</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Main KPIs</label>
        <length>3000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Priority_elements__c</fullName>
        <description>Ellen Community</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Priority elements</label>
        <length>3000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Timing_of_Integration__c</fullName>
        <description>“Ellen Community”</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Timing of Integration</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X2_3_Key_Messages__c</fullName>
        <description>“Ellen Community”</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>In consumer language, what are the 3 most important points to communicate in this integration?   PLEASE NOTE: Number of key messages included in integration will be determined by mutually agreed contract terms.</inlineHelpText>
        <label>2-3 Key Messages</label>
        <length>3000</length>
        <type>Html</type>
    </fields>
</CustomObject>

package objets and configuration/unpackaged/classes/Create_Lead_Community_Controller.cls
public without sharing class Create_Lead_Community_Controller {
    @AuraEnabled
    public static List<Map<String, String>> getOptions(){
        List<Map<String, String>> items = new List<Map<String, String>>();

        Schema.DescribeFieldResult fieldResult = Lead.Brand_Category__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            items.add(new Map<String, String>{'value' => pickListVal.getValue(), 'label' => pickListVal.getLabel()});
        }
        return items;
    }

    @AuraEnabled
    public static String create(String params){
        system.debug(params);

        try{
            Id RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Ellen Community').getRecordTypeId();
            Map<String, Object> data = (Map<String, Object>) JSON.deserializeUntyped(params);
            String Company = String.valueof(data.get('Company'));
            String LastName = String.valueof(data.get('LastName'));
            String BrandName = String.valueof(data.get('BrandName'));
            String Salutation = String.valueof(data.get('Salutation'));
            String FirstName = String.valueof(data.get('FirstName'));
            String phone = String.valueof(data.get('phone'));
            String BrandCategory = String.valueof(data.get('BrandCategory'));
            String Email = String.valueof(data.get('Email'));
            String Title = String.valueof(data.get('Title'));
            String TimingofIntegration = String.valueof(data.get('TimingofIntegration'));
            String Budget = String.valueof(data.get('Budget'));
            String KeyMessages = String.valueof(data.get('KeyMessages'));

            String importantthings = String.valueOf(data.get('importantthings'));
            String DetailsofMarketing = String.valueOf(data.get('DetailsofMarketing'));
            String MainKPIs = String.valueOf(data.get('MainKPIs'));
            String PriorityElements = String.valueOf(data.get('PriorityElements'));

            AssignmentRule AR = [select id,name from AssignmentRule where SobjectType = 'Lead' and Active = true and name='Ellen Lead Assignment' limit 1];
            Database.DMLOptions dmlOpts = new Database.DMLOptions();
            if(!Test.isRunningTest()){dmlOpts.assignmentRuleHeader.assignmentRuleId= AR.id;}else{dmlOpts.assignmentRuleHeader.useDefaultRule= true;}

            Lead l = new Lead();
            l.Company = Company;
            l.LastName = LastName;
            l.Brand_Name__c = BrandName;
            l.Salutation = Salutation;
            l.FirstName = FirstName;
            l.Phone = phone;
            l.Brand_Category__c = BrandCategory;
            l.Email = Email;
            l.Title = Title;
            l.Timing_of_Integration__c = TimingofIntegration;
            l.Budget__c = Budget;
            l.X2_3_Key_Messages__c = KeyMessages;
            l.Important_things_about_Brand__c = importantthings;
            l.Details_of_Marketing_Campaign__c = DetailsofMarketing;
            l.Main_KPIs__c = MainKPIs;
            l.Priority_elements__c = PriorityElements;
            l.RecordTypeId = RecordTypeId;
            insert l;

            l.setOptions(dmlOpts);
            update l;

            

            return 'Registered successfully';
        }catch(Exception e){
            System.debug(e.getMessage());
            System.debug(e.getTypeName());
            System.debug(e.getLineNumber());
            return e.getMessage();//'Failed to register, try in a few moments'; //e.getMessage();
        }

        
    }
}